### PR TITLE
Milestone2: Complete Transactions, Query, and Update the Animals Table.

### PR DESCRIPTION
**Pull request by carlylechia**
In order to complete this milestone, I:

- [x] Added a column, 'species' of type, 'string' to my `animals table` and modified my `schema.sql file`
- [x] Inserted 7 additional rows of data and modified my `data.sql file`
- [x] Inside a transaction, updated the `animals table` by setting the `species column` to *unspecified*. Verified that the change was made. Then rolled back the change and verified that the `species columns` went back to the state before the transaction.
- [x] Created two more transactions and updated the `animals table` according to the demands in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md)
- [x] All the updates made were recorded into the `data.sql file`
- [x] Wrote queries to answer all the questions posed in the **project requirements**, each query recorded into the `queries.sql file`

 ### **SCREENSHOTS**

1. **After the first commit:**
Screen Shot 2022-07-05 at 10 29 30

2. **After delete and rollback**
Screen Shot 2022-07-05 at 10 41 47

3. **After last transaction**
Screen Shot 2022-07-05 at 10 48 27

### CODE REVIEW

**Review by Davidosky007 — CHANGES_REQUESTED** [review]
Hi @carlylechia 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* Kindly update your query commands as your transactions and queries when ran, gave me the wrong results below ⬇️  is a screenshot of my result 
image
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carlylechia** [comment]
> Hi @carlylechia 👋,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * Kindly update your query commands as your transactions and queries when ran, gave me the wrong results below ⬇️  is a screenshot of my result
>   image
>   image
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi @Davidosky007 , I'm a little bit confused because all my queries and transactions are on point on my own IDE/terminal. Maybe you made a mistake somewhere. I'll attach a screenshot to this comment so that you can see my queries in action for yourself.
Screen Shot 2022-07-05 at 15 09 54

**Comment by carlylechia** [comment]
Please @Davidosky007 kindly look into this again...

**Review by Mre55 — APPROVED** [review]
**Hi @carlylechia,**

# Status: APPROVED 🏆 🎉 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- All queries result as expected  ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carlylechia** [comment]
Thank you @Mre55 !

**Pull request merged**
